FROM python:3.14-slim

WORKDIR /app-book

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY database.py ./
COPY models.py ./
COPY main.py ./

EXPOSE 8080

RUN useradd -m bookuser

USER bookuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
